### ISSUE TITLE
How to connect an old ANT-BMS

### ISSUE THREAD

**Issue by rdaguerre** [syssi/esphome-ant-bms#34]
Hello, is there a possibility to adapt it to use in the old ANT-BMS, Bluetooth version? Thank you

**Comment by syssi** [comment]
Could you describe your BMS model? Your version doesn't have a serial interface and can be controlled via Bluetooth only? Could you provide the APK of the Android app you are using to monitor/control the BMS?

**Comment by lucasimons** [comment]
all version of ant bms have the serial interface and bluetooth

**Comment by rdaguerre** [comment]
The App is My-BMS. Where can i use the serial interface? i try in Display port but not work
thanks.

![Screenshot_20220329-162522_MaYi-BMS 1](https://user-images.githubusercontent.com/44953932/160692097-297f2a69-fed4-4c06-874c-93350b177958.jpg)
![20220329_162453 1](https://user-images.githubusercontent.com/44953932/160692525-94f75912-2380-4cf3-aa5f-b9833ef25bbb.jpg)
S

**Comment by lucasimons** [comment]
The serial connection is  the one for the display

**Comment by rdaguerre** [comment]
i use this adapter and not work the comunication 
![20220329_190412 1](https://user-images.githubusercontent.com/44953932/160714970-8b36bf11-ae08-49b9-afa0-44e3e23c8ff0.jpg)

**Comment by syssi** [comment]
This implementation must be flashed to a ESP32 oder ESP8266. The USB-to-TTL converter is only useful if you want to connect the BMS to a computer. Could you provide a photo of your ESP connected to the BMS? So we can check your wiring is correct.

**Comment by rdaguerre** [comment]
Hi, thanks for the help. I managed to connect it directly from the Heltec esp32 to the old ANT-BMS and it works. The problem I'm having is that I can't get the bms to turn on. What should the ignition combination be? As for the wiring, it is the one that is explained. Thank you

**Comment by syssi** [comment]
If the esphome node loses the WiFi connection / the API connection to HA gets disconnected the entities will be shown as unavailable. As soon the connection to the ESP is back the sensors should be available again.

Could you explain the "how to turn the BMS on" question" a bit more in detail? If the BMS is powered off you want be able to start the BMS remotely or are you asking about the way to turn on the BMS in general (if it's powered off)?

**Comment by syssi** [comment]
@lucasimons Could you provide some details how to start the BMS? This is my understanding:

If you connect 3.3V and GND to the display port of the BMS the device should boot. If you add RX + TX you are able to read some data. If you disconnect 3.3V from the display port again the BMS don't want to communicate via RX/TX anymore. Can you confirm this?

@rdaguerre If you want to connect the display port "+" to some `GPIO` to remote control the BMS startup please make sure the "+" connector don't draw much current. If you see any current here you should use a transistor for switching via the GPIO. You are the first who makes this attempt!

**Comment by lucasimons** [comment]
> @lucasimons Could you provide some details how to start the BMS? This is my understanding:
> 
> If you connect `3.3V` and `GND` to the display port of the BMS the device should boot. If you connect `RX`, `TX` you are able to query data. If you disconnect `3.3V` from the display port again the BMS don't want to communicate via RX/TX anymore. Can you confirm this?
> 
> @rdaguerre If you want to connect the display port `+` to some `GPIO` to remote control the BMS startup please make sure the `+` connector don't draw much current. If you see any current here you should use a transistor for switching via the GPIO. You are the first who makes this attempt!

So if the bms is already on you can see the bluetooth, otherwise you have to feed it to 3.3 as in the figure but in reality to read the data you have to feed the two pins on the left and connect the two on the right to tx and rx

![image](https://user-images.githubusercontent.com/67467751/161375890-51a54953-d165-466b-b1e5-02e1c81a0fcd.png)
