### ISSUE TITLE
How to factory reset a ANT-BMS?

### ISSUE THREAD

**Issue by Stealthbomber76** [syssi/esphome-ant-bms#42]
Hello. Im pretty new to antbms and looking for help! I got all working but i dont know how all happen but the auth. locked me out. Regardless how i wrote the 123456789abc or whatever it gave me error as it was wrong. This would be in android app and even on pc. Now i do believe the fw got messed up. Is there away to install fw again and how to do or where to download? Thanks

**Comment by syssi** [comment]
Which model / hardware version of the BMS do you own exactly?

**Comment by Stealthbomber76** [comment]
Not sure the hardware but in one photo i take "20PHUB00-220716B" This bms is from 2021-07-14. 20PHB-TB-8-20S-300A model
