### ISSUE TITLE
Ant BMS 2021+ PC software

### ISSUE THREAD

**Issue by bchiu** [syssi/esphome-ant-bms#44]
I am also trying to decode the new protocol. Would you mind sharing the PC application?

**Comment by syssi** [comment]
https://nextcloud.turmzimmer.de/s/oSod3Ez4YSnmo7y

**Comment by syssi** [comment]
Feel free to close the issue if it's solved.

**Comment by bchiu** [comment]
much appreciated. dunno why this software is so hard to find.
