### ISSUE TITLE
Interface with ANT 32S 300A - Tested

### ISSUE THREAD

**Issue by JorgeTorres01** [syssi/esphome-ant-bms#70]
Hello,

I would like to leave only my test with the **ANT 32S 300A** .

I had some difficulty communicating with the BMS.
Through another topic I noticed that pins A, B is not RS485
I tested just connecting BMS to FTDI. 

![image](https://github.com/syssi/esphome-ant-bms/assets/10577951/47fd48cf-1fd1-47fa-8ff0-50e1623d7458)

![image](https://github.com/syssi/esphome-ant-bms/assets/10577951/bc8af3dd-2717-47ff-b2c6-5de3fef9c2c0)

**Comment by syssi** [comment]
It looks like your device is compatible with this implementation. Just give it a try! :-)

**Comment by syssi** [comment]
Did you try to change some settings (f.e. toggle the Mosfets) using this project? Is the old or new command set required?

**Comment by cng3035** [comment]
@JorgeTorres01
I have a ANT BMS 32S 200A that appears to have a very similar PCB as your 300A (same data pin layout).

I tried providing 3.3V to the V port but don't see any data on the "A" and "B" pin even with an oscilloscope.

Can you provide more details on how you hooked it up?
I'm using a generic "FT232RL" board and hooking up as follows

- VCC (in 3.3V mode) to the V pin on the bms
- GND to the G pin on the bms
- RX to A on the bms
- TX to B on the bms

**Comment by pwilkowski** [comment]
@cng3035 have you solved the issues?

**Comment by cng3035** [comment]
@pwilkowski Unfortunately no, was not able to get a wired serial connection working. Still using ant-bms-old-ble
