### ISSUE TITLE
Clarify schematics and connector type

### ISSUE THREAD

**Issue by syssi** [syssi/esphome-ant-bms#9]
1. The serial connection of the display is used!
2. VCC must be connected or not?
3. VCC is used to start the BMS?
4. The connector is a JST XH2.0 4P or JST/microMolex 1.25mm 4p?

**Comment by lucasimons** [comment]
2 the Vcc must be conneced
4 The connector is a JST/microMolex 1.25mm 4p

**Comment by syssi** [comment]
Thanks for your feedback. I will update the docs!
