### ISSUE TITLE
length of value must be at least 8 but the old BMS only 4

### ISSUE THREAD

**Issue by jinkexue** [syssi/esphome-ant-bms#91]
```
substitutions:
  name: ant-bms-old-ble
  device_description: "Monitor and control a ANT Battery Management System (ANT-BMS) via BLE"
  external_components_source: github://syssi/esphome-ant-bms@main
  # Apply the MAC address of your ANT-BMS here (BLE device name: "ANT-BLE24C"). Please don't use "BMS-ANT24C".
  mac_address: 16:aa:22:02:23:45
  password: "1234"

but feedback:

INFO Updating https://github.com/syssi/esphome-ant-bms.git@main
Failed config

ant_bms_old_ble: [source /config/esphome/ant32.yaml:96]
  - id: bms0
    ble_client_id: client0
    update_interval: 5s
    
    length of value must be at least 8.
    password: 1234
```

**Comment by jinkexue** [comment]
Failed config

ant_bms_old_ble: [source /config/esphome/ant32.yaml:97]
  - id: bms0
    ble_client_id: client0
    update_interval: 5s
    
    length of value must be at most 4.
    password: 12345678

could i change the bms password to  12345678  ?

**Comment by syssi** [comment]
The `1234` password should be accepted now. Please give it a try!

**Comment by jinkexue** [comment]
> The `1234` password should be accepted now. Please give it a try!

thanks, so quick 
at most 4 now ？
It seems I won’t be able to link to the BMS if I change the password to more than 4 digits

**Comment by syssi** [comment]
Do you know which password lengths are supported in general?

**Comment by cng3035** [comment]
> Do you know which password lengths are supported in general?

I currently have a 8 character password set and it was functional. The new change, `(min=4, max=4)`, is a breaking change for at least me and likely others.

I think an acceptable interim compromise would be
`cv.All(cv.string_strict, cv.Length(min=4, max=8)),`

**Comment by syssi** [comment]
Thanks for your feedback! I will revert the change because a 4 digit password won't work either at the moment.
