### ISSUE TITLE
Sensors update at different times

### ISSUE THREAD

**Issue by rdaguerre** [syssi/esphome-ant-bms#99]
Hello, I am seeing that the sensor values ​​are updated at different times even when I set the interval to be 3s in BLE.
How can I make 3 sensors, for example, update together. since I need to have correct data at the right time of the 3. thank you very much

**Comment by syssi** [comment]
Could you tell me the explicit sensors your are interested in?

**Comment by syssi** [comment]
I'm closing this issue because of no response.
